# Generated by Django 4.1.2 on 2023-01-17 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_avatar_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
